import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ReduxProvider } from "../store/ReduxProvider";
import "./globals.css";
import ServiceWorkerRegister from "../components/service-worker/register";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <link rel="manifest" href="/manifest.json" />
        <ReduxProvider>
          {children}
          {/* Register service worker on client side */}
          <ServiceWorkerRegister />
        </ReduxProvider>
      </body>
    </html>
  );
}
