import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { ReduxProvider } from '@/lib/redux';
//import { I18nProvider } from '../i18n/i18nProvider';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  // Keep layout server-rendered; Redux and I18n providers are client components so we mount them inside the body
  return (
    <html lang="it">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <link rel="manifest" href="/manifest.json" />
        <ReduxProvider>
          {/* <I18nProvider defaultLocale="it">
            {children}
          </I18nProvider> */}
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
